### ISSUE TITLE
Suche: Felder doppelt, fehlende Inhalte

### ISSUE THREAD

**Issue by drmenzelit** [Joomla-DACH/JoomlaDACH-Template#113]
In der Suche sind die Auswahlfelder doppelt:
![grafik](https://github.com/user-attachments/assets/2579072f-ef5f-4e44-85e7-bc1a83371029)

Verschiedene Inhalte (z.B. Tipps und Tricks) sind nicht indexiert. Ich habe auch im Backend geschaut, der Index scheint nicht komplett zu sein. Und bei Inhaltsstruktur sind auch Doppelungen:
![grafik](https://github.com/user-attachments/assets/ca18ebce-fce1-4d24-b0ab-633679589c4c)

**Comment by SniperSister** [comment]
See https://github.com/joomla/joomla-cms/issues/44289

**Comment by SniperSister** [comment]
Fixed
