### ISSUE TITLE
Finalisierung Dienstleisterverzeichnis

### ISSUE THREAD

**Issue by SniperSister** [Joomla-DACH/JoomlaDACH-Template#41]
* Registrierung
* ACL
* Formulare
* Übertragung bestehende Beiträge

**Comment by crimle** [comment]
Idee: Ein Filter mit dem nach Land und Bundesland/Kanton gefiltert werden kann.

**Comment by crimle** [comment]
Es ist wahrscheinlich nicht für alle selbsterklärend, dass man auf die Überschrift klicken muss, wenn man die Kontaktdetails anschauen will. Entweder sollten Sie schon in der Übersicht sichtbar sein. Oder ein zweiter Button [Details] neben [Zur Webseite] Ich habe das Gefühl es sollte schon in dieser Übersicht erkennbar sein, aus welchem Land/Region ein Dienstleister stammt.

**Comment by crimle** [comment]
Es sollte sichergestellt werden, dass die Firmenlogos und die Überschriften horizontal büdnig ausgerichtet sind, ungeachtet dessen, wie gross das Logo ist.

**Comment by crimle** [comment]
Hochladen von SVG Dateien ermöglichen

**Comment by SniperSister** [comment]
@crimle ich habe die Filter wie besprochen ergänzt und gestyled, einen Details button eingebaut und in der Übersicht die Ortsangaben hinzugefügt; SVGs können hochgeladen werden, die Ausrichtung ist gefixt. Siehst du noch offene Themen?

**Comment by crimle** [comment]
Sieht doch super aus! Vielen Dank!

Etwas unschön: die linke und die rechte Spalte des Blogs sehen unterschiedlich aus.
Das heisst: die Überschriften (div.page-header) sind vertikal versetzt:

**Comment by crimle** [comment]
In der Übersicht werden PLZ Kanton LAND angezeigt, aber der Ort fehlt:
![grafik](https://github.com/Joomla-DACH/JoomlaDACH-Template/assets/51155809/7b4b2765-0126-4485-9e37-493891f437d0)
Ich bin der Meinung, dass der Kanton hier nicht nötig ist; PLZ Ort und Land genügen. 

In der Detailansicht sehen wir Adresse, PLZ Ort, aber Kanton und Land fehlen.
![grafik](https://github.com/Joomla-DACH/JoomlaDACH-Template/assets/51155809/f71477e4-ab91-442e-b64c-93871eee66c8)

**Comment by SniperSister** [comment]
Ist angepasst

**Comment by crimle** [comment]
Auf mobilen Geräten (Hamburger-Menü) ist «Dienstleister» nicht anwählbar. Es klappt nur das Untermenü «Eintragen» auf und zu. Ist auch bei «Über Joomla» so.

**Comment by crimle** [comment]
Logos im SVG Format werden nicht immer angezeigt, zum Beispiel beim Eintrag «Weblight» sieht man das Logo nicht:
![grafik](https://github.com/Joomla-DACH/JoomlaDACH-Template/assets/51155809/31cefe5f-4db6-4128-b070-43a83a59b133)

Bei «Rimle IT Services» habe ich auch ein SVG Logo, aber dieses ist sichtbar. Verstehe ich nicht...

**Comment by crimle** [comment]
Bei der Dienstleistersuche ist «Tätigkeitsbereich» offenbar ein Pflichtfeld:
![grafik](https://github.com/Joomla-DACH/JoomlaDACH-Template/assets/51155809/b1aea2ac-5e9b-4974-b914-aeae72865f1f)
Wollen wir das wirklich als Pflichtfeld haben? Ich selbst bin auch in die Falle getappt und habe mehrmals auf den [Suchen] Button geklickt, ohne dass etwas passiert wäre.

**Comment by tecpromotion** [comment]
> Bei der Dienstleistersuche ist «Tätigkeitsbereich» offenbar ein Pflichtfeld: 
Wollen wir das wirklich als Pflichtfeld haben? Ich selbst bin auch in die Falle getappt und habe mehrmals auf den [Suchen] Button geklickt, ohne dass etwas passiert wäre.

Um eine Suche zu triggern sollte dies kein Pflichtfeld sein. Bzw. wenn nichts angegeben muss er mir ja alle Einträge zurückgeben, pro Land etc.

**Comment by crimle** [comment]
Ich musste die Liste - Region CH - überarbeiten. Anstelle der 25 Kantone gibt es nur noch die 7 Grossregionen. Grund: wir haben viele Kantone ohne Joomla-Dienstleister; da würde jedes mal eine leere Liste angezeigt. Das wollen wir verhindern.

**Comment by crimle** [comment]
Auf joomlaverband.ch hatten wir noch einen Filter «Joomla-Zertifizierung». Ich neige zur Meinung, auf diesen Filter zu verzichten, weil die Zertifizierung Joomla 3 betrifft und das schon relativ alt ist.

**Comment by crimle** [comment]
Das CH-Dienstleisterverzeichnis ist jetzt fertig! Bei den folgenden Beiträgen ist das Logo (SVG-Datei) unsichtbar:

MEDIARTS Webdesign & Grafik GmbH
Weblight GmbH

**Comment by SniperSister** [comment]
> Auf joomlaverband.ch hatten wir noch einen Filter «Joomla-Zertifizierung». Ich neige zur Meinung, auf diesen Filter zu verzichten, weil die Zertifizierung Joomla 3 betrifft und das schon relativ alt ist.

Da stimme ich zu

> Ich musste die Liste - Region CH - überarbeiten. Anstelle der 25 Kantone gibt es nur noch die 7 Grossregionen. Grund: wir haben viele Kantone ohne Joomla-Dienstleister; da würde jedes mal eine leere Liste angezeigt. Das wollen wir verhindern.

Danke!

> Auf mobilen Geräten (Hamburger-Menü) ist «Dienstleister» nicht anwählbar. Es klappt nur das Untermenü «Eintragen» auf und zu. Ist auch bei «Über Joomla» so.

Fixed, beim zweiten Klick wird der Parent Menüeintrag geladen

> Das CH-Dienstleisterverzeichnis ist jetzt fertig! Bei den folgenden Beiträgen ist das Logo (SVG-Datei) unsichtbar:

Die Grafiken sind falsch angelegt, die haben 0x0 pixel als height und width hinterlegt

**Comment by crimle** [comment]
`Die Grafiken sind falsch angelegt, die haben 0x0 pixel als height und width hinterlegt`
Ab die Grafik hat doch diese Definitionen:
`width="158" height="75"`
Schau mal hier:
![grafik](https://github.com/Joomla-DACH/JoomlaDACH-Template/assets/51155809/ce52804c-7409-4e6e-902e-e9e2b0ce3cde)
Und im Editor wird sie korrekt angezeigt. Es scheint einen Zusammenhang zum CSS zu geben. Hier wird die Breite auf 0 gesetzt:
![grafik](https://github.com/Joomla-DACH/JoomlaDACH-Template/assets/51155809/f36d9e60-777c-4940-8347-7f4c33878948)

**Comment by crimle** [comment]
![grafik](https://github.com/Joomla-DACH/JoomlaDACH-Template/assets/51155809/7c8d626e-ad39-47d7-aa52-8ee255b1d304)

**Comment by SniperSister** [comment]
> Ab die Grafik hat doch diese Definitionen: width="158" height="75"

Auf dem img tag ja, aber durch width und height auto im CSS greifen die in der SVG festgelegten Maße - oder genauer: die width und height Attribute auf dem `<svg>`-Tag. Die haben gefehlt. Ist manuell in den beiden svg Dateien nachgerüstet.
