### ISSUE TITLE
Übertragung Events

### ISSUE THREAD

**Issue by SniperSister** [Joomla-DACH/JoomlaDACH-Template#42]

**Comment by crimle** [comment]
Event-Komponente installieren (DP Calendar?).

**Comment by tecpromotion** [comment]
Das machen wir mit Joomla-Beiträgen. Dafür ist keine Erweiterung notwendig.

**Comment by SniperSister** [comment]
@tecpromotion wie handhaben wir die Events der JUGs?

**Comment by tecpromotion** [comment]
Wie bisher wäre da mein Vorschlag. Die Pflege über Google Kalender ist simple und etabliert.

**Comment by SniperSister** [comment]
Indeed - und da hätte DP den Vorteil des direkten Imports gehabt, dann müssten wir das Bestandsmodul nicht für J4/5 portieren

**Comment by tecpromotion** [comment]
Aber wir haben dann DP an der Backe...

**Comment by tecpromotion** [comment]
Aber beuge mich da natürlich.

**Comment by SniperSister** [comment]
Allon macht nen guten Job. Hab ich keinen Bauchschmerz bei.

**Comment by crimle** [comment]
> Wie bisher wäre da mein Vorschlag. Die Pflege über Google Kalender ist simple und etabliert.

Habt Ihr in Deutschland nicht eine sehr strenge DSGVO? Wie passt ein Google-Kalender dazu, wenn sogar die Google-Fonts «böse» sind?

**Comment by SniperSister** [comment]
@crimle der Kalender ist nur die Datenquelle, die eigentliche Ausgabe erfolgt direkt im Markup der Seite und der Browser des Endnutzers hat keinen Kontakt mit Google

**Comment by crimle** [comment]
Ok, der Endbenutzer nicht. Aber die «sensiblen» Event-Daten sind bei Google auf einem «bösen» Server in den USA gespeichert. Versteh' mich richtig: ich sehe das Thema ohnehin viel lockerer als die DSGVO. Für **mich** ist Google-Kalender eh kein Problem. Ich dachte nur...

**Comment by SniperSister** [comment]
Die DSGVO schützt *personenbezogene* Daten. Ein Event ist keine Person und daher unproblematisch :)

**Comment by crimle** [comment]
Wäre es nicht cool und wünschenswert, wenn man sich zu diesen Events auch gleich **anmelden** könnte? Das wäre mit Joomla-Beiträgen nicht möglich?!

**Comment by crimle** [comment]
Kann ich irgendwie behilflich sein? Ich würde mich ja gerne um den Bereich «Events» kümmern. Aber wir müssen genau die Bedürfnisse definieren und dann festlegen, wie bzw. mit welchem Tool wir das machen. Ich habe das Gefühl, Joomla-Beiträge bieten nicht genug Möglichkeiten. Der DP Calendar sieht attraktiv aus, bietet verschiedene Kalender-Ansichten, die Möglichkeit einen Lageplan anzuzeigen finde ich ebenfalls cool. Die Möglichkeit, sich für eine Veranstaltung anzumelden, ist fast schon ein Pflichtkriterium. Zuguterletzt sind auch Ticketverkäufe möglich (analog JoomlaDay).

**Comment by crimle** [comment]
Wir haben die Anforderung «Anmeldemöglichkeit für Events» bei uns im Vorstand diskutiert. Diese Anforderung ziehen wir zurück. Wir werden die Anmeldung auf joomlaverband.ch anbieten. Somit steht der Realisierung mit Joomla-Beiträgen nichts im Weg.

**Comment by SniperSister** [comment]
Ich würde das mit DP machen, dann haben wir im weiteren Verlauf alle Möglichkeiten. Kümmere mich drum!

**Comment by crimle** [comment]
Es geht das Gerücht, dass das GoLive Ende Januar geplant sei. Kann ich etwas helfen?

**Comment by crimle** [comment]
Ich habe mal die mir bekannten Events erfasst.

**Comment by SniperSister** [comment]
Danke!

**Comment by SniperSister** [comment]
Sowohl die "großen", manuell in DP gepflegten Events als auch die JUG Events sind übernommen:
* https://dach.joomla.de/community/events
* https://dach.joomla.de/community/joomla-usergroups
