### ISSUE TITLE
Start-Modul für News um Bilder ergänzen

### ISSUE THREAD

**Issue by SniperSister** [Joomla-DACH/JoomlaDACH-Template#48]

**Comment by tecpromotion** [comment]
@svom News und Bildmaterial ist nun auf Stand.

**Comment by svom** [comment]
Besprochen ist das folgende:

Anstatt der bisherigen Ansicht wird ein dreispaltiges News-Modul implementiert. Je Eintrag die folgenden Inhalte:

- Bild
- Headline
- Datum Autor
- Dann Excerpt
- Weiterlesen

**Comment by svom** [comment]
Erledigt. PR dazu ist raus.
