### ISSUE TITLE
Mobile Navigation zeigt falsche Seiten an

### ISSUE THREAD

**Issue by crimle** [Joomla-DACH/JoomlaDACH-Template#56]
Die mobile Navigation ist irgendwie durcheinandergeraten. Wenn man «Community» anklickt, gelangt man zur Seite «Anforderungen», wählt man «Dienstleister, erscheint «Joomla!-Projekt-Roadmap» und so weiter.

**Comment by SniperSister** [comment]
Durch #58 gefixt. Da lag die zweite Menüebene unsichtbar drüber
