### ISSUE TITLE
Joomla!-Veranstaltungen

### ISSUE THREAD

**Issue by crimle** [Joomla-DACH/JoomlaDACH-Template#65]
Ich bin der Meinung, dass der Veranstaltungskalender ziemlich gut versteckt ist. Vorschlag:

- Im Hauptmenü einen Eintrag «Events» hinzufügen, der nach https://dach.joomla.de/community/events verweist
- Die JUG-Termine ebenfalls im Veranstaltungskalender auflisten *
- Einen Filter - Deutschland -, - Österreich - und - Schweiz - einbauen *

* ich würde das übernehmen, wenn Einigkeit besteht

**Comment by SniperSister** [comment]
> Im Hauptmenü einen Eintrag «Events» hinzufügen, der nach https://dach.joomla.de/community/events verweist

Wir hatten in der Konzeption der Seite lange darüber gesprochen, dass die Seite ihren inhaltlichen Schwerpunkt bei der Darstellung des Produkts, nicht bei der Darstellung der Community haben sollte, ein neue Obermenüpunkt bringt diesen Schwerpunkt für mich durcheinander.

> Die JUG-Termine ebenfalls im Veranstaltungskalender auflisten *

Dann wird die Liste sehr umfangreich - da hab ich Bauchschmerzen, denn die "großen" Events verlieren dann ihren USP in der Darstellung.

**Comment by crimle** [comment]
So wie es jetzt ist, ist es doch beinahe perfekt:

- Untermenü bei Community > «Joomla-Veranstaltungen»
- Monats-Ansicht des Kalenders als Default
- JUG-Termine sind auch ersichtlich, haben aber eine andere Farbe

Mir würde nur die Bezeichnung «Events» besser gefallen (moderner, kürzer). «Veranstaltungen» tönt für mich etwas sperrig. Ist aber nicht schlimm.

**Comment by SniperSister** [comment]
Name ist angepasst!
