### ISSUE TITLE
add space from header

### ISSUE THREAD

**Issue by tecpromotion** [Joomla-DACH/JoomlaDACH-Template#70]
@svom ich brauche hier bitte einen universellen Abstand, wenn kein Headermodule etc geladen wird. Einfach Überschrift der Kategorie, Menüpunkt, etc.

Beispiele:

- https://dach.joomla.de/wissen/joomla-event-videos
- https://dach.joomla.de/wissen/joomla-tipps-im-advent

Detailseite dürfen auch etwas mehr Abstand von oben haben, wenn kein Bild geladen wird.

Beispiel: 

- https://dach.joomla.de/wissen/joomla-tipps-im-advent/tag-24-www-joomla-day-at

**Comment by svom** [comment]
Habe dir nen PR zugewiesen.
