### ISSUE TITLE
template layout for events with youtube-snippet (Event Videos)

### ISSUE THREAD

**Issue by tecpromotion** [Joomla-DACH/JoomlaDACH-Template#71]
Ich habe die Inhalte übertragen und das Vlog Plugin eingerichtet.

Wir brauchen nun ein Template Layout zur Ausgabe der Daten.
Ziel ist, die Detailseite um das Video zu ergänzen und wenn möglich, da gepflegt, das Level (Farbe) im Kategorieblog und der Detailseite zu nutzen.

Kategorieblog: https://dach.joomla.de/wissen/joomla-event-videos und https://dach.joomla.de/wissen/joomla-event-videos/joomla-day-deutschland

Detailseite: https://dach.joomla.de/wissen/joomla-event-videos/joomla-day-deutschland/jd22dach-update-auf-joomla-4-und-dann-kommt-5

**Comment by SniperSister** [comment]
Ich habe das Plugin mal auf aktuelle Standards portiert.

Lukas, schaust du nach dem Layout?
