### ISSUE TITLE
Modul: mod_articles_latest - Boxes

### ISSUE THREAD

**Issue by svom** [Joomla-DACH/JoomlaDACH-Template#8]
<img width="469" alt="Bildschirmfoto 2023-05-12 um 17 16 52" src="https://github.com/Joomla-DACH/JoomlaDACH-Template/assets/14434412/9b3ba9bc-14f2-4f80-851c-621af38e5a11">

**Comment by svom** [comment]
mod_boxes ist gebaut. Daran kann man sich bezüglich des Markups orientieren.

**Comment by svom** [comment]
Frage ist, ob wir die Variante als mod_articles_latest in diesem Fall überhaupt noch brauchen. Würde aber sicherlich auch nicht schaden mit Blick auf eine flexible Ausgestaltung möglicher Inhalte.

**Comment by SniperSister** [comment]
ich würde es mir erstmal sparen
