### ISSUE TITLE
fehlende J!Otto Bereich auf neuer Webseite

### ISSUE THREAD

**Issue by eumel1602** [Joomla-DACH/JoomlaDACH-Template#85]
Hallo!
Da ich niemanden in die Parade fahren möchte, wollte ich hier fragen, ob es geplant ist den J!Otto Award wieder mit einem Menülink auf joomla.de zu präsentieren? 
Auch dieses Jahr soll die 9. Verleihung stattfinden.  Werbung und Erklärungen könnten dauerhaft über das Menü ähnlich früher sichtbar gemacht werden. 
Kann jemand was dazu sagen? 

Gruss MArco

**Comment by tecpromotion** [comment]
Was genau möchtest du künftig da abbilden?
Gefunden habe ich diesen Beitrag: https://www.joomla.de/news/events/j-otto-award-2021-bewerbung-fuer-die-besten-website-mit-joomlaumsetzung

Da passt aber Inhalt nicht wirklich zur URL und Datum. 

Alternativ wäre mein Vorschlag, dass simple mit Tags und als News in der Kategorie News einfach zu schreiben. Über den Tag wäre ein Menüpunkt Kategorienlog in Community doch ganz nett.

**Comment by eumel1602** [comment]
Genau Diese Seite sollte auf der alten joomla.de version im Menü verlinkt gewesen sein. Den alias und das Datum habe ich noch nicht angepasst bzw aktuell noch vergessen. Theoretisch reicht dieser Beitrag als fester link im Menü (Community?), das wenn jemand sucht eine Info findet und zur Jotto Webseite kommt. 

Da es, ausser Anpassungen in diesem einen Beitrag, (z.b. bei ende der Einreichungsphase) keine großen News geben wird, sollte ein blog unter dem Menülink nicht gebraucht werden.  

**edit:** Das bild muss von mir auch noch geändert werden...

**Comment by tecpromotion** [comment]
Ok. Lege ich dir an und machen da ein paar redirects mit sauberen URLs.

**Comment by eumel1602** [comment]
ok. danke

**Comment by tecpromotion** [comment]
erledigt: https://www.joomla.de/community/j-otto-joomla-award
