### ISSUE TITLE
Abstände im Dropdown groß

### ISSUE THREAD

**Issue by webgras** [Joomla-DACH/JoomlaDACH-Template#90]
Ich finde die Abstände im Dropdown zu groß oder das Padding zu klein.
![grafik](https://github.com/Joomla-DACH/JoomlaDACH-Template/assets/10774704/5f5b6096-8c58-4159-b33e-46a849a78efe)

**Comment by SniperSister** [comment]
Done!

**Comment by webgras** [comment]
besser als vorher :-)
etwas padding könnten die li's noch vertragen ;-), aber ich kenne das ursprüngliche Design ja nicht

**Comment by SniperSister** [comment]
Kann dir nicht folgen, wo genau willst du npch padding haben?

**Comment by webgras** [comment]
also da außen klebt das relativ weit am Rand finde ich
![grafik](https://github.com/Joomla-DACH/JoomlaDACH-Template/assets/10774704/54651caa-8ec0-4c7a-ad01-8af8db609c62)

**Comment by SniperSister** [comment]
@webgras klebt weit am rand = du willst mehr padding? Oder weniger?

**Comment by webgras** [comment]
ich will mehr padding

**Comment by SniperSister** [comment]
So besser?

**Comment by webgras** [comment]
definitely :-)

**Comment by webgras** [comment]
danke!
