### ISSUE TITLE
Dienstleister-Suchergebnisse immer leer

### ISSUE THREAD

**Issue by webgras** [Joomla-DACH/JoomlaDACH-Template#93]
Wenn auch direkt auf den Menüpunkt Dienstleister klicke, sind die Einträge in der Liste.
Sobald ich auf ein Bundesland klicke, kommen keine Ergebnisse.

Es macht auch keinen Sinn, dass man gleichzeitig nach einem Bundesland in D und AT oder CH suchen kann
![grafik](https://github.com/Joomla-DACH/JoomlaDACH-Template/assets/10774704/0a28e224-489f-4b1c-955f-a9f57f925cea)

**Comment by SniperSister** [comment]
![Bildschirmfoto 2024-03-21 um 09 21 21](https://github.com/Joomla-DACH/JoomlaDACH-Template/assets/498096/ea8a0db5-11cd-475e-854e-1d14785df22d)

Dass die Ergebnisse grundsätlzich leer sind kann ich nicht reproduzieren, es kommt halt aufs Bundesland an

> Es macht auch keinen Sinn, dass man gleichzeitig nach einem Bundesland in D und AT oder CH suchen kann

Fixed

**Comment by webgras** [comment]
hm, kann es sein, dass - wenn ich eingeloggt war im Frontend - dann nur mein eigenes Ergebnis bekommen? egal, wonach ich suche?

Stefan hat mir gestern einen User angelegt, damit ich meinen Eintrag bearbeiten kann. Und eigentlich waren ab da dann die Suchergebnisse leer.

**Comment by SniperSister** [comment]
> hm, kann es sein, dass - wenn ich eingeloggt war im Frontend - dann nur mein eigenes Ergebnis bekommen? egal, wonach ich suche?

Hm, ich wüsste nicht warum. Wir nutzen da Akeeba Flter magic, der hat dafür eigentlich keine Logik

**Comment by webgras** [comment]
hm, heute geht es und ich bekomme überall Ergebnisse.
