### ISSUE TITLE
Nicht alle TAGS werden ausgegeben

### ISSUE THREAD

**Issue by tecpromotion** [Joomla-DACH/JoomlaDACH-Template#99]
Auf der Detailseite https://www.joomla.de/news/joomla/joomla-5-1-1-und-joomla-4-4-5-veroeffentlicht und auf der Übersicht https://www.joomla.de/news wird scheinbar immer nur der erste TAG ausgegeben.

**Comment by svom** [comment]
![Bildschirmfoto 2024-07-10 um 16 06 17](https://github.com/Joomla-DACH/JoomlaDACH-Template/assets/14434412/7e7c56fd-87d0-46b7-94c1-0c7e1fc37d1f)
